using System.Linq;
using NUnit.Framework;
using STVrogue.GameLogic;
using STVrogue.Utils;
using static STVrogue.Utils.HelperPredicates;

namespace NUnitTests
{
    [TestFixture]
    
    // An example of a test that is is mostly generated by CoPilot. It helps,
    // but you have to put critical eyes on the suggestions. It is also not
    // perfect so you have to fix some things manually.
    // Still, it can be help in producing starting code.
    public class Test_Dungeon
    {
        // This a parameterized test for the constructor of the Dungeon class, in particular for
        // the linear shaped dungeon. The test is parameterized over the number of rooms N and
        // the maximum capacity of the rooms.
       [TestCase(2,3)]
       [TestCase(3,0)]
       [TestCase(3,1)]
       [TestCase(3,2)]
       [TestCase(3,3)]
       public void test_LinearDungeon(int N, int capacity)
        {
            Dungeon dungeon = new Dungeon(new RandomGenerator(123), DungeonShapeType.LINEAR,N,capacity);
            // we have N rooms:
            Assert.IsTrue(dungeon.Rooms.Count == N);
            // each room has a unique ID:
            Assert.IsTrue(Forall(dungeon.Rooms, r => dungeon.Rooms.Count(r2 => r2.Id == r.Id) == 1));
            // each room has a capacity between 0 and capacity:
            Assert.That(Forall(dungeon.Rooms, r => r.Capacity >= 0 && r.Capacity <= capacity));
            // there is a unique startroom:
            Assert.IsTrue(dungeon.StartRoom != null);
            Assert.IsTrue(dungeon.Rooms.Count(r => r == dungeon.StartRoom) == 1);
            // there is a unique exitroom:
            Assert.IsTrue(dungeon.ExitRoom != null);
            Assert.IsTrue(dungeon.Rooms.Count(r => r == dungeon.ExitRoom) == 1);
            // all rooms are reachable from the startroom:
            Forall(dungeon.Rooms, r => dungeon.StartRoom.ReachableRooms().Contains(r));
        }
    }
}